version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    tty: true
    restart: always
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      # PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
